name = "autoview"
type = "javascript"
account_id = "294c98cb3633c3a8a8ead5e5e82f02b1"
workers_dev = true
compatibility_date = "2025-03-07"

[build]
command = "npm install && npm run build"
main = "dist/worker.js"
